# Generated by Django 3.2.5 on 2023-03-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='close_bal',
            field=models.FloatField(default=0),
        ),
    ]
