# Generated by Django 3.2.5 on 2023-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticks_app', '0002_balance_close_bal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capacity',
            old_name='saving',
            new_name='income',
        ),
        migrations.AddField(
            model_name='capacity',
            name='end_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capacity',
            name='savings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capacity',
            name='spend_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capacity',
            name='start_date',
            field=models.IntegerField(default=0),
        ),
    ]
